'use strict';
const APP_VERSION='v6.0';
const KEY='karol_coca_state_v1';const $=s=>document.querySelector(s);const esc=x=>String(x??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
const now=()=>new Date().toLocaleString('es-MX');
const normalize=x=>String(x??'').toLocaleLowerCase('es').normalize('NFD').replace(/[\u0300-\u036f]/g,'').trim();
function group(p){const n=normalize(p.name);if(n.startsWith('coca cola'))return /retornable|vidrio(?!\s+desechable)|taquera/.test(n)&&!/vidrio\s+light|vidrio\s+sin/.test(n)?'Coca-Cola retornable':'Coca-Cola desechable';if(/^(fanta|fresca|sprite|sidral|sangria|delaware)/.test(n))return 'Refrescos de sabores';if(/^(jugo|frutsi|fuze|limon & nada|naranja & nada|leche|lechita|del valle)/.test(n))return 'Jugos y otras bebidas';if(/^(agua|topochico)/.test(n))return 'Aguas';return 'Energéticas y otras';}
const GROUPS=['Coca-Cola desechable','Coca-Cola retornable','Refrescos de sabores','Jugos y otras bebidas','Aguas','Energéticas y otras'];
function vol(s){const n=normalize(s);const m=n.match(/(?:^|\s)(\d+(?:[.,]\d+)?)\s*(ml|lt|l|gl|oz)(?=\s|$)/);if(!m)return 0;const v=Number(m[1].replace(',','.'));return v*({ml:1,lt:1000,l:1000,gl:3785.41,oz:29.5735}[m[2]]||1)}
function sortProducts(a,b){let g=GROUPS.indexOf(group(a))-GROUPS.indexOf(group(b));if(g)return g;return (Number(b.customRank??vol(b.name))-Number(a.customRank??vol(a.name)))||a.name.localeCompare(b.name,'es')}
function emptyState(){return {products:INITIAL_CATALOG.map((p,i)=>({...p,id:'p'+(i+1),customRank:null})),order:{},history:[],pinHash:null,phone:'',copyPhone:'526469475354',lastBackup:0,changes:[],initialized:now()}}
let state;try{const s=JSON.parse(localStorage.getItem(KEY));state=s&&Array.isArray(s.products)?s:emptyState()}catch{state=emptyState()};if(!Array.isArray(state.changes))state.changes=[];if(state.copyPhone===undefined)state.copyPhone='526469475354';if(state.sendPending===undefined)state.sendPending=null;
const save=()=>{try{localStorage.setItem(KEY,JSON.stringify(state));return true}catch{alert('No se pudo guardar. El almacenamiento del navegador podría estar lleno o deshabilitado. Haz un respaldo y reduce las fotografías.');return false}};
const go=view=>{page=view;selected.clear();render()};let page='home',catalogTab='active',search='',selected=new Set(),notice='';let displayMode=localStorage.getItem('karol_coca_view')||'list';
function keycode(p){return p.code||p.id}function active(){return state.products.filter(p=>p.status==='active')}function picked(){return state.products.filter(p=>(state.order[p.id]||0)>0).sort(sortProducts)}function total(){return picked().reduce((a,p)=>a+state.order[p.id],0)}
function viewSwitch(){return `<div class="view-switch"><button class="${displayMode==='list'?'':'secondary'}" data-view="list">☰ Lista</button><button class="${displayMode==='cards'?'':'secondary'}" data-view="cards">▦ Tarjetas</button></div>`}
function head(t,desc=''){return `<h2>${esc(t)}</h2>${desc?`<p class="sub">${esc(desc)}</p>`:''}`}
function render(){const nav=[['home','Inicio'],['order','Nuevo pedido'],['review','Revisar'],['history','Historial'],['catalog','Catálogo'],['settings','Configuración']];$('#nav').innerHTML=nav.map(([id,label])=>`<button class="${page===id?'selected':''}" data-go="${id}">${label}</button>`).join('');let html='';if(notice){html+=`<div class="note">${esc(notice)}</div>`;notice=''}
if(page==='home')html+=`<div class="grid">${[['order','🛒','Nuevo pedido'],['history','🕘','Historial'],['catalog','📦','Catálogo'],['settings','⚙️','Configuración']].map(([id,icon,name])=>`<button class="tile" data-go="${id}"><span>${icon}</span>${name}</button>`).join('')}</div><div class="panel" style="margin-top:16px"><div class="stats"><div class="stat"><b>${state.products.length}</b>Productos</div><div class="stat"><b>${active().length}</b>Activos</div><div class="stat"><b>${picked().length}</b>En pedido</div><div class="stat"><b>${total()}</b>Cajas</div></div><p class="sub">${Object.values(state.order).some(v=>v>0)?'Existe un pedido pendiente. Puedes continuar o comenzar uno nuevo.':'No hay productos seleccionados en el pedido actual.'}</p>${picked().length?'<button data-action="resetAsk" class="secondary">Comenzar uno nuevo</button>':''}</div>`;
if(page==='order')html+=head('Nuevo pedido','Selecciona productos activos con los botones + y −.')+`<div class="panel"><div class="stats"><div class="stat"><b>${picked().length}</b>Productos</div><div class="stat"><b>${total()}</b>Cajas</div></div><div class="tools"><input id="find" placeholder="Buscar por nombre o presentación" value="${esc(search)}"><button class="secondary" data-action="clearSearch">Limpiar búsqueda</button></div><div class="row"><button data-go="review">Ver pedido (${picked().length})</button><button class="secondary" data-action="resetAsk">Pedido nuevo en cero</button></div></div>`+viewSwitch()+listByGroup(active().filter(p=>normalize(p.name).includes(normalize(search))),true);
if(page==='review')html+=head('Revisión antes de compartir')+`<div class="panel"><div class="stats"><div class="stat"><b>${picked().length}</b>Productos</div><div class="stat"><b>${total()}</b>Cajas</div></div><div class="tools"><button data-go="order" class="secondary">Corregir pedido</button><button data-action="share" ${picked().length?'':'disabled'}>Compartir por WhatsApp</button>${state.sendPending&&picked().length?'<button data-action="confirmPending">Confirmar envío pendiente</button>':''}<button class="secondary" data-action="copy" ${picked().length?'':'disabled'}>Copiar texto</button></div></div>`+renderList(picked(),true)+(picked().length?`<div class="panel"><h3>Vista del mensaje</h3><textarea readonly>${esc(message())}</textarea></div>`:'<div class="panel">Tu pedido está vacío.</div>');
if(page==='catalog')html+=head('Administración del catálogo','Los productos inactivos no aparecen en los pedidos nuevos.')+`<div class="panel"><div class="tabs"><button data-tab="active" class="${catalogTab==='active'?'on':''}">ACTIVOS (${active().length})</button><button data-tab="inactive" class="${catalogTab==='inactive'?'on':''}">INACTIVOS (${state.products.length-active().length})</button></div><div class="tools"><input id="find" placeholder="Buscar producto o código" value="${esc(search)}"><button data-action="add">Agregar producto</button><button data-action="import">Importar Excel</button></div><div class="tools"><button class="secondary" data-action="selectAll">Seleccionar visibles</button><button class="secondary" data-action="clearSelection">Quitar selección</button><button data-action="toggleSelected" ${selected.size?'':'disabled'}>${catalogTab==='active'?'Inactivar':'Activar'} seleccionados (${selected.size})</button></div></div>`+renderList(state.products.filter(p=>p.status===catalogTab).filter(p=>(normalize(p.name)+' '+p.code).includes(normalize(search))).sort(sortProducts),false);
if(page==='history')html+=head('Historial de pedidos',`${state.history.length} pedidos guardados`)+`<div class="panel tools"><button class="danger" data-action="clearHistory" ${state.history.length?'':'disabled'}>Vaciar historial</button></div>`+(state.history.length?state.history.map(h=>`<div class="panel"><div class="row between"><strong>${esc(h.date)}</strong><span class="sub">${h.items.length} productos · ${h.items.reduce((x,i)=>x+i.qty,0)} cajas</span></div><div class="tools"><button class="secondary mini" data-action="viewHistory" data-id="${esc(h.id)}">Consultar</button><button class="secondary mini" data-action="resend" data-id="${esc(h.id)}">Reenviar</button><button class="secondary mini" data-action="reuse" data-id="${esc(h.id)}">Reutilizar</button><button class="danger mini" data-action="deleteHistory" data-id="${esc(h.id)}">Eliminar</button></div></div>`).join(''):'<div class="panel">Todavía no hay pedidos en el historial.</div>');
if(page==='settings')html+=head('Configuración y respaldo')+`<div class="panel"><h3>Seguridad</h3><p class="sub">${state.pinHash?'PIN configurado. Se solicita para cada operación administrativa.':'Aún no existe PIN de administrador. Configúralo antes de administrar el catálogo.'}</p><div class="tools"><button data-action="setPin">${state.pinHash?'Cambiar PIN':'Configurar PIN'}</button></div><h3>WhatsApp</h3><p class="sub">Número fijo opcional, con clave de país y sin espacios (ejemplo: 526461234567). Si se deja vacío, se elegirá el destinatario al compartir.</p><div class="tools"><input id="phone" inputmode="numeric" value="${esc(state.phone||'')}" placeholder="52..."/><button data-action="savePhone">Guardar preventa</button></div><h3>Copia del pedido</h3><p class="sub">El envío de copia siempre se prepara por separado. Debes confirmar en WhatsApp cada mensaje; la app no puede enviarlos automáticamente.</p><div class="tools"><input id="copyPhone" inputmode="numeric" value="${esc(state.copyPhone||'')}" placeholder="52..."/><button data-action="saveCopyPhone">Guardar número de copia</button></div><h3>Respaldo</h3><p class="sub">Se incluyen catálogo, estados, pedido pendiente, historial y configuración. Respaldo anterior: ${state.lastBackup?new Date(state.lastBackup).toLocaleString('es-MX'):'ninguno'}.</p><div class="tools"><button data-action="backup">Exportar respaldo JSON</button><button class="secondary" data-action="restore">Restaurar respaldo</button></div><p class="note">El PIN protege cambios dentro de la interfaz, pero no sustituye la seguridad del dispositivo. Los datos locales se pueden perder al limpiar el navegador. Los recordatorios de respaldo se mostrarán al abrir la aplicación.</p></div>`;
$('#root').innerHTML=html;bindInputs();}
function bindInputs(){const f=$('#find');if(f){f.addEventListener('input',e=>{const x=e.target.value;search=x;const start=e.target.selectionStart;render();const n=$('#find');if(n){n.focus();n.setSelectionRange(start,start)}})} }
function listByGroup(arr,inOrder){const groups=GROUPS.filter(g=>arr.some(p=>group(p)===g));return groups.map(g=>`<section class="panel"><h3>${esc(g)}</h3>${renderList(arr.filter(p=>group(p)===g).sort(sortProducts),inOrder)}</section>`).join('')||'<div class="panel">No se encontraron productos.</div>'}
function renderList(arr,inOrder){const cards=displayMode==='cards'&&inOrder;return `<div class="list ${cards?'cards':''}">${arr.map(p=>`<div class="item ${cards?'product-card':''}">${p.photo?`<button type="button" class="photo-btn" ${inOrder?`data-qty="${esc(p.id)}" data-diff="1" aria-label="Agregar caja de ${esc(p.name)}"`:`data-action="edit" data-id="${esc(p.id)}"`}><img src="${p.photo}" alt="${esc(p.name)}" loading="lazy"></button>`:''}<div class="desc">${inOrder?'':`<input class="check" type="checkbox" data-select="${esc(p.id)}" ${selected.has(p.id)?'checked':''} aria-label="Seleccionar ${esc(p.name)}">`}<strong>${esc(p.name)}</strong><small>${esc(p.code)} ${inOrder?'':` · <span class="tag ${p.status==='active'?'':'off'}">${p.status==='active'?'ACTIVO':'INACTIVO'}</span>`}</small></div>${inOrder?`<div class="qty"><button class="secondary" aria-label="Quitar caja" data-qty="${p.id}" data-diff="-1">−</button><b>${state.order[p.id]||0}</b><button aria-label="Agregar caja" data-qty="${p.id}" data-diff="1">+</button></div>`:`<button class="secondary mini" data-action="edit" data-id="${p.id}">Editar</button>`}</div>`).join('')}</div>`}
function message(items=picked().map(p=>({name:p.name,qty:state.order[p.id]})),date=new Date()){return ['MINIMARKET KAROL','FECHA: '+date.toLocaleDateString('es-MX'),'PEDIDO COCA-COLA','',...items.map(i=>`${i.name} — ${i.qty} ${i.qty===1?'CAJA':'CAJAS'}`),'',`${items.length} PRODUCTOS · ${items.reduce((a,i)=>a+i.qty,0)} CAJAS`].join('\n')}
function modal(content){$('#modalContent').innerHTML=content;$('#modal').showModal()};function closeModal(){$('#modal').close()};function ask(text){return confirm(text)};
async function pinCheck(){if(!state.pinHash){alert('Primero configura el PIN en Configuración.');go('settings');return false}const pin=prompt('Introduce el PIN de administrador (4 dígitos):');if(pin===null)return false;if(!/^\d{4}$/.test(pin)||await hash(pin)!==state.pinHash){alert('PIN incorrecto.');return false}return true}
// SHA-256 local fallback for file:// pages, where crypto.subtle may be unavailable.
function sha256Local(input){
 const bytes=new TextEncoder().encode(input), bitLen=bytes.length*8;
 const size=Math.ceil((bytes.length+9)/64)*64, m=new Uint8Array(size);m.set(bytes);m[bytes.length]=128;
 const v=new DataView(m.buffer);v.setUint32(size-8,Math.floor(bitLen/4294967296),false);v.setUint32(size-4,bitLen>>>0,false);
 const K=[0x428a2f98,0x71374491,0xb5c0fbcf,0xe9b5dba5,0x3956c25b,0x59f111f1,0x923f82a4,0xab1c5ed5,0xd807aa98,0x12835b01,0x243185be,0x550c7dc3,0x72be5d74,0x80deb1fe,0x9bdc06a7,0xc19bf174,0xe49b69c1,0xefbe4786,0x0fc19dc6,0x240ca1cc,0x2de92c6f,0x4a7484aa,0x5cb0a9dc,0x76f988da,0x983e5152,0xa831c66d,0xb00327c8,0xbf597fc7,0xc6e00bf3,0xd5a79147,0x06ca6351,0x14292967,0x27b70a85,0x2e1b2138,0x4d2c6dfc,0x53380d13,0x650a7354,0x766a0abb,0x81c2c92e,0x92722c85,0xa2bfe8a1,0xa81a664b,0xc24b8b70,0xc76c51a3,0xd192e819,0xd6990624,0xf40e3585,0x106aa070,0x19a4c116,0x1e376c08,0x2748774c,0x34b0bcb5,0x391c0cb3,0x4ed8aa4a,0x5b9cca4f,0x682e6ff3,0x748f82ee,0x78a5636f,0x84c87814,0x8cc70208,0x90befffa,0xa4506ceb,0xbef9a3f7,0xc67178f2];
 const H=[0x6a09e667,0xbb67ae85,0x3c6ef372,0xa54ff53a,0x510e527f,0x9b05688c,0x1f83d9ab,0x5be0cd19],w=new Uint32Array(64);
 const r=(n,k)=>(n>>>k)|(n<<(32-k));
 for(let off=0;off<size;off+=64){
  for(let j=0;j<16;j++)w[j]=v.getUint32(off+4*j,false);
  for(let j=16;j<64;j++){const a=w[j-15],b=w[j-2];w[j]=(w[j-16]+(r(a,7)^r(a,18)^(a>>>3))+w[j-7]+(r(b,17)^r(b,19)^(b>>>10)))>>>0}
  let [a,b,c,d,e,f,g,h]=H;
  for(let j=0;j<64;j++){const t1=(h+(r(e,6)^r(e,11)^r(e,25))+((e&f)^(~e&g))+K[j]+w[j])>>>0;const t2=((r(a,2)^r(a,13)^r(a,22))+((a&b)^(a&c)^(b&c)))>>>0;h=g;g=f;f=e;e=(d+t1)>>>0;d=c;c=b;b=a;a=(t1+t2)>>>0}
  [a,b,c,d,e,f,g,h].forEach((n,i)=>H[i]=(H[i]+n)>>>0);
 }
 return H.map(n=>n.toString(16).padStart(8,'0')).join('');
}
async function hash(x){const input='minimarket-karol-pin-v1:'+x;if(typeof crypto!=='undefined'&&crypto.subtle){try{const buf=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(input));return Array.from(new Uint8Array(buf)).map(b=>b.toString(16).padStart(2,'0')).join('')}catch(e){/* fallback below */}}return sha256Local(input)}
async function setPin(){if(state.pinHash&&!(await pinCheck()))return;const a=prompt('Define un PIN de 4 dígitos (no lo compartas):');if(a===null)return;if(!/^\d{4}$/.test(a))return alert('Deben ser exactamente 4 dígitos.');const b=prompt('Repite el PIN:');if(a!==b)return alert('Los PIN no coinciden.');state.pinHash=await hash(a);save();render();alert('PIN configurado.')}
function download(name,data,type){const blob=new Blob([data],{type});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1200)};
function backup(){const data=JSON.stringify({...state,backupVersion:1,exported:now()},null,2);download('respaldo_coca_karol_'+new Date().toISOString().slice(0,10)+'.json',data,'application/json');state.lastBackup=Date.now();save();render()}
function fileInput(accept,callback){const i=document.createElement('input');i.type='file';i.accept=accept;i.addEventListener('change',async()=>{if(i.files?.[0])try{await callback(i.files[0])}catch(e){alert('No se pudo leer el archivo: '+e.message)}});i.click()}
async function restore(){if(!(await pinCheck()))return;fileInput('.json,application/json',async f=>{const obj=JSON.parse(await f.text());if(!Array.isArray(obj.products)||!Array.isArray(obj.history)||!obj.products.every(p=>p.id&&p.name))throw Error('No es un respaldo válido de la app.');if(!ask('Se reemplazará toda la información actual. ¿Continuar?'))return;state={...obj};save();go('home');alert('Respaldo restaurado.')})}
function optimizePhoto(file){return new Promise((resolve,reject)=>{if(!file.type.startsWith('image/'))return reject(Error('Selecciona una imagen.'));const img=new Image(),url=URL.createObjectURL(file);img.onload=()=>{const side=850,scale=Math.min(1,side/Math.max(img.width,img.height));const canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(img.width*scale));canvas.height=Math.max(1,Math.round(img.height*scale));const ctx=canvas.getContext('2d');ctx.drawImage(img,0,0,canvas.width,canvas.height);URL.revokeObjectURL(url);resolve(canvas.toDataURL('image/jpeg',.72))};img.onerror=()=>{URL.revokeObjectURL(url);reject(Error('No fue posible procesar la fotografía.'))};img.src=url})}
async function scanBarcode(setCode){
 if(!('BarcodeDetector'in window)){alert('Este navegador no permite escanear códigos directamente. Usa la captura manual o un lector USB.');return}
 if(!navigator.mediaDevices?.getUserMedia){alert('La cámara requiere HTTPS y permiso de cámara.');return}
 let stream=null,running=true,busy=false;
 try{
  stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'},width:{ideal:1280},height:{ideal:720}},audio:false});
  let formats=['ean_13','ean_8','upc_a','upc_e','code_128'];
  if(BarcodeDetector.getSupportedFormats){const supported=await BarcodeDetector.getSupportedFormats();formats=formats.filter(x=>supported.includes(x));}
  const detector=new BarcodeDetector(formats.length?{formats}:undefined);
  modal('<h2>Escanear código</h2><video id="scanVideo" autoplay muted playsinline style="width:100%;border-radius:12px;background:#111"></video><p class="sub">Apunta al código de barras y mantenlo dentro de la imagen.</p><p id="scanStatus" class="sub">Preparando cámara…</p>');
  const video=$('#scanVideo'),dialog=$('#modal'),status=$('#scanStatus');video.srcObject=stream;video.muted=true;video.setAttribute('playsinline','');
  const stop=()=>{running=false;stream?.getTracks().forEach(t=>t.stop());};dialog.addEventListener('close',stop,{once:true});
  await new Promise((resolve,reject)=>{if(video.readyState>=1&&video.videoWidth)resolve();else{const timer=setTimeout(()=>reject(Error('La cámara no entregó imagen a tiempo.')),10000);video.addEventListener('loadedmetadata',()=>{clearTimeout(timer);resolve()},{once:true})}});
  await video.play();
  while(running&&dialog.open){
   if(!busy&&video.readyState>=2&&video.videoWidth>0&&video.videoHeight>0){busy=true;try{const codes=await detector.detect(video);if(codes?.length){const code=String(codes[0].rawValue||'').trim();if(code){stop();closeModal();setCode(code);return}}if(status)status.textContent='Buscando código…';}catch(err){if(status)status.textContent='Buscando código…';}finally{busy=false}}
   await new Promise(r=>setTimeout(r,180));
  }
 }catch(e){alert('No se pudo usar la cámara: '+(e?.message||e))}finally{running=false;stream?.getTracks().forEach(t=>t.stop())}
}
function showEdit(id){const p=state.products.find(x=>x.id===id);modal(`<h2>${p?'Editar producto':'Agregar producto'}</h2><div class="list"><label>Nombre completo<br><input class="wide" id="editName" value="${esc(p?.name||'')}"></label><label>Código de barras (se puede completar después)<br><input class="wide" id="editCode" inputmode="numeric" value="${esc(p?.code||'')}"></label><button class="secondary" id="scanCode">📷 Escanear código con cámara</button><label>Estado<br><select id="editStatus"><option value="active" ${p?.status!=='inactive'?'selected':''}>ACTIVO</option><option value="inactive" ${p?.status==='inactive'?'selected':''}>INACTIVO</option></select></label><label>Fotografía del producto (opcional)<br><input class="wide" type="file" id="photoFile" accept="image/*"></label><button class="secondary" id="takePhoto">📷 Tomar fotografía</button>${p?.photo?`<div><img src="${p.photo}" style="max-height:170px;max-width:100%"><br><button class="secondary" id="removePhoto">Quitar fotografía</button></div>`:''}<button id="saveEdit">Guardar producto</button></div>`);let newPhoto=p?.photo||null;$('#scanCode').onclick=()=>{const beforeName=$('#editName').value,beforeStatus=$('#editStatus').value;scanBarcode(code=>{showEdit(id);$('#editName').value=beforeName;$('#editStatus').value=beforeStatus;$('#editCode').value=code})};$('#takePhoto').onclick=()=>{const input=$('#photoFile');input.setAttribute('capture','environment');input.click()};$('#photoFile').onchange=async e=>{try{const f=e.target.files?.[0];if(f){newPhoto=await optimizePhoto(f);alert('Fotografía lista para guardar.')}}catch(err){alert(err.message)}};if($('#removePhoto'))$('#removePhoto').onclick=()=>{newPhoto=null;alert('La fotografía se quitará al guardar.');};$('#saveEdit').onclick=()=>{const name=$('#editName').value.trim(),code=$('#editCode').value.trim(),status=$('#editStatus').value;if(!name)return alert('Indica el producto.');if(code&&!/^\d{8,14}$/.test(code))return alert('El código de barras debe tener de 8 a 14 dígitos.');if(code&&state.products.some(x=>x.id!==id&&x.code===code))return alert('Código de barras repetido.');if(p)Object.assign(p,{name,code,status,photo:newPhoto});else state.products.push({id:'p'+Date.now(),name,code,status,customRank:null,photo:newPhoto});save();closeModal();render()}}
function parseCSV(txt){const lines=txt.replace(/^\uFEFF/,'').split(/\r?\n/).filter(x=>x.trim());const sep=(lines[0]||'').includes('\t')?'\t':(lines[0]||'').split(';').length>(lines[0]||'').split(',').length?';':',';return lines.map(line=>{let out=[],str='',quoted=false;for(let i=0;i<line.length;i++){const c=line[i];if(c==='"'){if(quoted&&line[i+1]==='"'){str+='"';i++}else quoted=!quoted}else if(c===sep&&!quoted){out.push(str);str=''}else str+=c}out.push(str);return out})}
async function readZip(file){const b=await file.arrayBuffer(),d=new DataView(b);let end=-1;for(let i=b.byteLength-22;i>=Math.max(0,b.byteLength-65557);i--)if(d.getUint32(i,true)===0x06054b50){end=i;break}if(end<0)throw Error('El archivo no es ZIP/XLSX válido');const count=d.getUint16(end+10,true),offset=d.getUint32(end+16,true);let pos=offset,out={};for(let j=0;j<count;j++){if(d.getUint32(pos,true)!==0x02014b50)break;const method=d.getUint16(pos+10,true),size=d.getUint32(pos+20,true),nlen=d.getUint16(pos+28,true),extra=d.getUint16(pos+30,true),comment=d.getUint16(pos+32,true),local=d.getUint32(pos+42,true),name=new TextDecoder().decode(new Uint8Array(b,pos+46,nlen));if(name==='xl/sharedStrings.xml'||/^xl\/worksheets\/sheet\d+\.xml$/.test(name)){const start=local+30+d.getUint16(local+26,true)+d.getUint16(local+28,true);let bytes=new Uint8Array(b.slice(start,start+size));if(method===8){const stream=new Blob([bytes]).stream().pipeThrough(new DecompressionStream('deflate-raw'));bytes=new Uint8Array(await new Response(stream).arrayBuffer())}else if(method!==0)throw Error('Método de compresión XLSX no soportado');out[name]=new TextDecoder().decode(bytes)}pos+=46+nlen+extra+comment}return out}
async function readExcel(file){if(/\.csv$/i.test(file.name))return parseCSV(await file.text());if(!/\.xlsx$/i.test(file.name))throw Error('Usa un archivo .xlsx o .csv');const xmls=await readZip(file),parser=new DOMParser(),ss=[];if(xmls['xl/sharedStrings.xml']){const doc=parser.parseFromString(xmls['xl/sharedStrings.xml'],'text/xml');doc.querySelectorAll('si').forEach(si=>ss.push([...si.querySelectorAll('t')].map(t=>t.textContent).join('')))}const sheet=xmls['xl/worksheets/sheet1.xml'];if(!sheet)throw Error('No se encontró la primera hoja de Excel');const doc=parser.parseFromString(sheet,'text/xml');return [...doc.querySelectorAll('sheetData > row')].map(row=>{const cells=[];row.querySelectorAll('c').forEach(c=>{const column=c.getAttribute('r').match(/^[A-Z]+/)[0];let idx=0;for(const letter of column)idx=idx*26+letter.charCodeAt(0)-64;const value=c.querySelector('v')?.textContent??c.querySelector('is')?.textContent??'';cells[idx-1]=c.getAttribute('t')==='s'?ss[Number(value)]??'':value});return cells})}
function importDialog(){modal('<h2>Importar catálogo Excel</h2><p>Columnas obligatorias: <b>A = Código de barras</b>, <b>B = Producto</b>, <b>C = STATUS</b>. También se acepta CSV con las mismas columnas.</p><p class="sub">Para productos existentes se conserva el STATUS de la app. Para productos nuevos se respeta INACTIVO o campo vacío (= ACTIVO). Los productos nuevos sin código se incorporan con identificador interno.</p><button id="chooseExcel">Elegir archivo Excel o CSV</button>');$('#chooseExcel').onclick=()=>fileInput('.xlsx,.csv',async f=>{const rows=await readExcel(f);let added=0,updated=0,skipped=0,duplicates=0;const seen=new Set();for(const r of rows){let code=String(r[0]??'').trim(),name=String(r[1]??'').trim(),status=normalize(r[2]);if(!name||normalize(name)==='producto'||normalize(code)==='codigo'||normalize(code)==='código'){skipped++;continue}if(code&&!/^\d{8,14}$/.test(code)){skipped++;continue}let k=code||'name:'+normalize(name);if(seen.has(k)){duplicates++;continue}seen.add(k);let p=code?state.products.find(p=>p.code===code):state.products.find(p=>!p.code&&normalize(p.name)===normalize(name));if(p){p.name=name;updated++}else{state.products.push({id:'p'+Date.now()+'_'+added,code,name,status:status==='inactivo'?'inactive':'active',customRank:null});added++}}save();closeModal();render();alert(`Importación terminada: ${added} nuevos, ${updated} actualizados, ${skipped} omitidos y ${duplicates} repetidos en el archivo.`)})}
async function toggleSelected(){if(!selected.size)return;if(!(await pinCheck()))return;const status=catalogTab==='active'?'inactive':'active';const n=selected.size;if(!ask(`${status==='active'?'Activar':'Inactivar'} ${n} productos seleccionados?`))return;state.products.forEach(p=>{if(selected.has(p.id))p.status=status});selected.clear();save();render()}
function showHistory(id){const h=state.history.find(h=>h.id===id);if(!h)return;modal(`<h2>Pedido del ${esc(h.date)}</h2><p>${h.items.length} productos · ${h.items.reduce((x,i)=>x+i.qty,0)} cajas</p><textarea readonly>${esc(message(h.items,new Date(h.iso)))}</textarea>`)}
function shareText(txt,number=''){const url='https://wa.me/'+number+'?text='+encodeURIComponent(txt);window.open(url,'_blank','noopener,noreferrer')}
function share(){
 const txt=message();state.sendPending={stage:'main',started:new Date().toISOString()};save();
 if(state.phone){modal('<h2>Enviar pedido al preventa</h2><p>Elige el destinatario:</p><div class="tools"><button id="fixed">Preventa guardado</button><button id="another" class="secondary">Elegir otro contacto</button></div>');
 $('#fixed').onclick=()=>{closeModal();shareText(txt,state.phone);confirmSent()};
 $('#another').onclick=()=>{closeModal();shareText(txt);confirmSent()};
 }else{modal('<h2>Enviar pedido</h2><p>No hay número fijo del preventa. WhatsApp permitirá elegir un contacto.</p><button id="chooseContact">Elegir destinatario</button>');$('#chooseContact').onclick=()=>{closeModal();shareText(txt);confirmSent()}}
}
function finishSent(){
 const items=picked().map(p=>({code:p.code,name:p.name,qty:state.order[p.id]}));if(!items.length)return;
 state.history.unshift({id:'h'+Date.now(),date:now(),iso:new Date().toISOString(),items});state.order={};state.sendPending=null;save();closeModal();go('home');alert('Pedido guardado en historial. Se inició uno nuevo en cero.');
}
function confirmCopy(){
 modal(`<h2>Copia del pedido</h2><p>Envía una copia por WhatsApp al número <b>${esc(state.copyPhone||'no configurado')}</b>.</p><p class="sub">Se intentó abrir WhatsApp con la copia. Si el navegador bloqueó la ventana, pulsa «Abrir WhatsApp para copia». Debes pulsar Enviar en WhatsApp.</p><div class="tools"><button id="openCopy" ${state.copyPhone?'':'disabled'}>Abrir WhatsApp para copia</button><button id="confirmCopy" class="secondary">Ya envié la copia</button></div><button id="retryMain" class="secondary">No se envió la copia; mantener pendiente</button>`);
 $('#openCopy').onclick=()=>shareText(message(),state.copyPhone);
 $('#confirmCopy').onclick=()=>{if(confirm('¿Confirmas que también enviaste la copia por WhatsApp?'))finishSent()};
 $('#retryMain').onclick=closeModal;
}
function confirmSent(){
 modal('<h2>Confirmar envío al preventa</h2><p>¿El pedido se envió realmente por WhatsApp al preventa?</p><div class="tools"><button id="yesSent">Sí, continuar con la copia</button><button class="secondary" id="notSent">No, conservar pendiente</button></div><p class="sub">Abrir WhatsApp no garantiza que se haya enviado. La copia se abrirá en un segundo paso.</p>');
 $('#yesSent').onclick=()=>{state.sendPending={stage:'copy',started:state.sendPending?.started||new Date().toISOString()};save();if(state.copyPhone){shareText(message(),state.copyPhone);confirmCopy()}else{confirmCopy()}};$('#notSent').onclick=closeModal;
}
async function action(type,id){switch(type){case'resetAsk':if(ask('¿Descartar el pedido pendiente y empezar en cero?')){state.order={};save();go('order')}break;case'clearSearch':search='';render();break;case'copy':await navigator.clipboard.writeText(message()).then(()=>alert('Texto copiado.')).catch(()=>{modal(`<h3>Copiar pedido</h3><textarea readonly>${esc(message())}</textarea>`)});break;case'share':share();break;case'confirmPending':if(state.sendPending?.stage==='copy')confirmCopy();else confirmSent();break;case'add':if(await pinCheck())showEdit();break;case'edit':if(await pinCheck())showEdit(id);break;case'import':if(await pinCheck())importDialog();break;case'selectAll':state.products.filter(p=>p.status===catalogTab&&(normalize(p.name)+' '+p.code).includes(normalize(search))).forEach(p=>selected.add(p.id));render();break;case'clearSelection':selected.clear();render();break;case'toggleSelected':await toggleSelected();break;case'setPin':await setPin();break;case'savePhone':if(await pinCheck()){const v=$('#phone').value.trim();if(v&&!/^\d{10,15}$/.test(v))return alert('Número inválido; usa de 10 a 15 dígitos, incluyendo país.');state.phone=v;save();render();alert('Preventa guardado.')}break;case'saveCopyPhone':if(await pinCheck()){const v=$('#copyPhone').value.trim();if(!/^\d{10,15}$/.test(v))return alert('Introduce entre 10 y 15 dígitos, incluyendo país.');state.copyPhone=v;save();render();alert('Número de copia guardado.')}break;case'backup':if(await pinCheck())backup();break;case'restore':await restore();break;case'viewHistory':showHistory(id);break;case'resend':{let h=state.history.find(h=>h.id===id);if(h)shareText(message(h.items,new Date(h.iso)),state.phone||'');break}case'reuse':{const h=state.history.find(h=>h.id===id);if(!h)return;if(!ask('Reutilizar este pedido como nuevo pedido? Reemplazará las cantidades pendientes.'))return;state.order={};h.items.forEach(i=>{let p=state.products.find(p=>p.code&&p.code===i.code)||state.products.find(p=>p.name===i.name);if(p&&p.status==='active')state.order[p.id]=i.qty});save();go('order');break}case'deleteHistory':if(await pinCheck()&&ask('¿Eliminar este pedido del historial de forma definitiva?')){state.history=state.history.filter(h=>h.id!==id);save();render()}break;case'clearHistory':if(await pinCheck()&&ask('¿Eliminar TODOS los pedidos del historial? Esta operación es irreversible.')){state.history=[];save();render()}break;}}
document.addEventListener('click',e=>{const b=e.target.closest('[data-go],[data-action],[data-qty],[data-tab],[data-view]');if(!b)return;if(b.dataset.view){displayMode=b.dataset.view;localStorage.setItem('karol_coca_view',displayMode);render();return}if(b.dataset.go){go(b.dataset.go);return}if(b.dataset.tab){catalogTab=b.dataset.tab;selected.clear();render();return}if(b.dataset.qty){const id=b.dataset.qty,d=Number(b.dataset.diff);state.order[id]=Math.max(0,(state.order[id]||0)+d);if(state.order[id]===0)delete state.order[id];save();render();return}if(b.dataset.action)action(b.dataset.action,b.dataset.id)});
document.addEventListener('change',e=>{if(e.target.matches('[data-select]')){e.target.checked?selected.add(e.target.dataset.select):selected.delete(e.target.dataset.select);render()}});
if('serviceWorker'in navigator&&location.protocol!=='file:')navigator.serviceWorker.register('./sw.js').catch(()=>{});
if(state.lastBackup&&Date.now()-state.lastBackup>7*86400000)notice='Han pasado más de 7 días desde el último respaldo. Puedes exportarlo en Configuración.';
if(!state.lastBackup)notice='Importante: configura tu PIN de administrador y realiza un respaldo periódico del catálogo.';
render();
